import {
  CommunityListingComment,
  CommunityListingCommentLike,
  CommunityListingLike,
  Appointment,
  CommunityPost,
  CommunityPostComment,
  CommunityPostCommentLike,
  CommunityPostLike,
  Favorite,
  Listing,
  Property,
  SavedSearch,
  SellerMessage,
  User
} from "@/lib/types";

const now = new Date().toISOString();

export const seedUsers: User[] = [
  { id: "u-buyer-1", name: "Nour Hassan", email: "buyer@example.com", phone: "+201000000001", role: "BUYER", password: "123456", createdAt: now, updatedAt: now },
  { id: "u-seller-1", name: "Cairo Developments", email: "seller@example.com", phone: "+201000000002", role: "SELLER", password: "123456", createdAt: now, updatedAt: now },
  { id: "u-admin-1", name: "Platform Admin", email: "admin@example.com", phone: "+201000000003", role: "ADMIN", password: "123456", createdAt: now, updatedAt: now }
];

export const seedListings: Listing[] = [
  { id: "l-1", userId: "u-seller-1", status: "APPROVED", createdAt: now, updatedAt: now, reviewedBy: "u-admin-1", reviewedAt: now, adminNotes: "Looks good." },
  { id: "l-2", userId: "u-seller-1", status: "APPROVED", createdAt: now, updatedAt: now, reviewedBy: "u-admin-1", reviewedAt: now, adminNotes: "Verified ownership docs." },
  { id: "l-3", userId: "u-seller-1", status: "PENDING", createdAt: now, updatedAt: now },
  { id: "l-4", userId: "u-seller-1", status: "REJECTED", createdAt: now, updatedAt: now, reviewedBy: "u-admin-1", reviewedAt: now, adminNotes: "Low quality photos, please resubmit." },
  { id: "l-5", userId: "u-seller-1", status: "APPROVED", createdAt: now, updatedAt: now, reviewedBy: "u-admin-1", reviewedAt: now, adminNotes: "Contract checked." },
  { id: "l-6", userId: "u-seller-1", status: "APPROVED", createdAt: now, updatedAt: now, reviewedBy: "u-admin-1", reviewedAt: now, adminNotes: "Ready to publish." }
];

export const seedProperties: Property[] = [
  {
    id: "p-1",
    listingId: "l-1",
    title: "Cheque & Key Signature Apartment",
    description: "Prime apartment in Fifth Settlement with modern finishing and installment plans.",
    transaction: "BUY",
    type: "APARTMENT",
    price: 4200000,
    rentPrice: null,
    currency: "EGP",
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 185,
    lat: 30.0238,
    lng: 31.4921,
    address: "North 90 Street",
    city: "Cairo",
    area: "New Cairo",
    district: "North 90 Street",
    furnishing: "SEMI",
    paymentType: "INSTALLMENTS",
    completionStatus: "READY",
    amenities: ["A/C", "Balcony", "Parking", "Gym", "Security"],
    images: ["https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=1200"],
    installmentDownPayment: 840000,
    installmentYears: 8,
    installmentMonthly: 35000,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "p-2",
    listingId: "l-2",
    title: "Maadi Garden Villa",
    description: "Elegant standalone villa in Degla with private garden and pool.",
    transaction: "BUY",
    type: "VILLA",
    price: 11500000,
    rentPrice: null,
    currency: "EGP",
    bedrooms: 5,
    bathrooms: 4,
    areaSqm: 430,
    lat: 29.9628,
    lng: 31.2756,
    address: "Degla Main Road",
    city: "Cairo",
    area: "Maadi",
    district: "Degla",
    furnishing: "FULLY",
    paymentType: "CASH",
    completionStatus: "READY",
    amenities: ["A/C", "Balcony", "Parking", "Pool", "Garden", "Security"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200"],
    installmentDownPayment: null,
    installmentYears: null,
    installmentMonthly: null,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "p-3",
    listingId: "l-3",
    title: "Pending Penthouse in Heliopolis",
    description: "Under review listing in Korba with skyline views.",
    transaction: "BUY",
    type: "PENTHOUSE",
    price: 6900000,
    rentPrice: null,
    currency: "EGP",
    bedrooms: 4,
    bathrooms: 3,
    areaSqm: 250,
    lat: 30.0916,
    lng: 31.3185,
    address: "Korba Square",
    city: "Cairo",
    area: "Heliopolis",
    district: "Korba",
    furnishing: "UNFURNISHED",
    paymentType: "INSTALLMENTS",
    completionStatus: "OFF_PLAN",
    amenities: ["A/C", "Elevator", "Security"],
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200"],
    installmentDownPayment: 1380000,
    installmentYears: 10,
    installmentMonthly: 39000,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "p-4",
    listingId: "l-4",
    title: "Rejected Commercial Space",
    description: "Commercial property returned for correction.",
    transaction: "RENT",
    type: "COMMERCIAL",
    price: null,
    rentPrice: 85000,
    currency: "EGP",
    bedrooms: 0,
    bathrooms: 2,
    areaSqm: 310,
    lat: 30.0632,
    lng: 31.3281,
    address: "El Nozha",
    city: "Cairo",
    area: "Heliopolis",
    district: "El Nozha",
    furnishing: "SEMI",
    paymentType: "CASH",
    completionStatus: "READY",
    amenities: ["Parking", "Security"],
    images: ["https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200"],
    installmentDownPayment: null,
    installmentYears: null,
    installmentMonthly: null,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "p-5",
    listingId: "l-5",
    title: "Serviced Apartment for Rent - New Cairo",
    description: "High-end furnished rental near business hubs.",
    transaction: "RENT",
    type: "APARTMENT",
    price: null,
    rentPrice: 45000,
    currency: "EGP",
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 140,
    lat: 30.028,
    lng: 31.478,
    address: "Fifth Settlement",
    city: "Cairo",
    area: "New Cairo",
    district: "Fifth Settlement",
    furnishing: "FULLY",
    paymentType: "CASH",
    completionStatus: "READY",
    amenities: ["A/C", "Balcony", "Parking", "Gym", "Pets Allowed"],
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200"],
    installmentDownPayment: null,
    installmentYears: null,
    installmentMonthly: null,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "p-6",
    listingId: "l-6",
    title: "Vacation Chalet - North Coast Access Hub",
    description: "Chalet listing marketed from Cairo office with flexible payment schedule.",
    transaction: "VACATION",
    type: "CHALET",
    price: 3200000,
    rentPrice: null,
    currency: "EGP",
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 110,
    lat: 30.05,
    lng: 31.21,
    address: "October Gardens Hub",
    city: "Giza",
    area: "6th of October",
    district: "October Gardens",
    furnishing: "SEMI",
    paymentType: "INSTALLMENTS",
    completionStatus: "OFF_PLAN",
    amenities: ["Pool", "Parking", "Pets Allowed", "Security"],
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200"],
    installmentDownPayment: 480000,
    installmentYears: 7,
    installmentMonthly: 28000,
    createdAt: now,
    updatedAt: now
  }
];

export const seedFavorites: Favorite[] = [
  { id: "fav-1", userId: "u-buyer-1", propertyId: "p-1", createdAt: now },
  { id: "fav-2", userId: "u-buyer-1", propertyId: "p-5", createdAt: now }
];

export const seedAppointments: Appointment[] = [];
export const seedSavedSearches: SavedSearch[] = [];
export const seedSellerMessages: SellerMessage[] = [];
export const seedCommunityPosts: CommunityPost[] = [];
export const seedCommunityPostLikes: CommunityPostLike[] = [];
export const seedCommunityPostCommentLikes: CommunityPostCommentLike[] = [];
export const seedCommunityPostComments: CommunityPostComment[] = [];
export const seedCommunityListingLikes: CommunityListingLike[] = [];
export const seedCommunityListingCommentLikes: CommunityListingCommentLike[] = [];
export const seedCommunityListingComments: CommunityListingComment[] = [];
